import Config as Conf
import Lib.Tags as Tags

SRC_BASE = Conf.SOURCE_base
TGT_BASE = Conf.TARGET_base
SOURCE_USERNAME = Conf.SOURCE_USERNAME
TARGET_USERNAME = Conf.TARGET_USERNAME
SOURCE_PASSWORD = Conf.SOURCE_PASSWORD
TARGET_PASSWORD = Conf.TARGET_PASSWORD
RESPONSEXML = Conf.RESPONSEXML
RESPONSE_FILEARRAY = Tags.getTags(SRC_BASE,SOURCE_USERNAME,SOURCE_PASSWORD,RESPONSEXML)
Tags.processTagsResponse(RESPONSE_FILEARRAY)
Tags.setTags(TGT_BASE,TARGET_USERNAME,TARGET_PASSWORD)


